/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.predium.view;

import com.mycompany.predium.controller.OrdemServicoController;
import com.mycompany.predium.utils.KeyboardUtils;
import com.mycompany.predium.utils.WindowUtils;
import javax.swing.JOptionPane;

/**
 *
 * @author MarquesV
 */
public class AtualizarStatusJDialog extends javax.swing.JDialog {
    
    private OrdemServicoController ordemController;

    /**
     * Creates new form AtualizarStatusJDialog
     */
    public AtualizarStatusJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.ordemController = new OrdemServicoController();
        WindowUtils.centralizarTela(this);
        KeyboardUtils.configurarEnterParaBotao(atualizarJButton);
        KeyboardUtils.configurarEnterParaBotao(cancelarJButton);
    }

    public void setOrdemInfo(String ordemId, String descricao, String statusAtual, String local) {
        ordemIDJLabel.setText("Ordem Selecionada: {ID: " + ordemId + "}");
        ordemDescricaoJLabel.setText("Descrição: " + descricao);
        ordemStatusAtualJLabel.setText("Status Atual: " + statusAtual);
        ordemLocalJLabel.setText("Local: " + local);
        campoAEditarJComboBox.setSelectedItem(statusAtual); // Seleciona o status atual no JComboBox
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cancelarJButton = new javax.swing.JButton();
        atualizarJButton = new javax.swing.JButton();
        tituloJLabel = new javax.swing.JLabel();
        ordemIDJLabel = new javax.swing.JLabel();
        ordemDescricaoJLabel = new javax.swing.JLabel();
        ordemStatusAtualJLabel = new javax.swing.JLabel();
        campoAEditarJLabel = new javax.swing.JLabel();
        campoAEditarJComboBox = new javax.swing.JComboBox<>();
        ordemLocalJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Atualizar Status - Predium");

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setPreferredSize(new java.awt.Dimension(804, 720));

        cancelarJButton.setBackground(new java.awt.Color(187, 187, 187));
        cancelarJButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelarJButton.setForeground(new java.awt.Color(0, 0, 0));
        cancelarJButton.setText("Cancelar");
        cancelarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarJButtonActionPerformed(evt);
            }
        });

        atualizarJButton.setBackground(new java.awt.Color(30, 149, 115));
        atualizarJButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        atualizarJButton.setForeground(new java.awt.Color(255, 255, 255));
        atualizarJButton.setText("Atualizar Status");
        atualizarJButton.setFocusTraversalPolicyProvider(true);
        atualizarJButton.setNextFocusableComponent(cancelarJButton);
        atualizarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarJButtonActionPerformed(evt);
            }
        });

        tituloJLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tituloJLabel.setForeground(new java.awt.Color(0, 0, 0));
        tituloJLabel.setText("Atualizar Status da Ordem");

        ordemIDJLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ordemIDJLabel.setForeground(new java.awt.Color(0, 0, 0));
        ordemIDJLabel.setText("Ordem Selecionada: {ID da ordem}");

        ordemDescricaoJLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ordemDescricaoJLabel.setForeground(new java.awt.Color(0, 0, 0));
        ordemDescricaoJLabel.setText("Descrição: {Descrição da Ordem}");

        ordemStatusAtualJLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ordemStatusAtualJLabel.setForeground(new java.awt.Color(0, 0, 0));
        ordemStatusAtualJLabel.setText("Status Atual: {Status da Ordem}");

        campoAEditarJLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoAEditarJLabel.setForeground(new java.awt.Color(0, 0, 0));
        campoAEditarJLabel.setText("Novo Status:");

        campoAEditarJComboBox.setBackground(new java.awt.Color(255, 255, 255));
        campoAEditarJComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        campoAEditarJComboBox.setForeground(new java.awt.Color(0, 0, 0));
        campoAEditarJComboBox.setMaximumRowCount(4);
        campoAEditarJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aberta", "Andamento", "Concluída", "Cancelada" }));
        campoAEditarJComboBox.setFocusTraversalPolicyProvider(true);
        campoAEditarJComboBox.setNextFocusableComponent(atualizarJButton);
        campoAEditarJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoAEditarJComboBoxActionPerformed(evt);
            }
        });

        ordemLocalJLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ordemLocalJLabel.setForeground(new java.awt.Color(0, 0, 0));
        ordemLocalJLabel.setText("Local: {Local da Ordem}");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ordemIDJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ordemDescricaoJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addComponent(campoAEditarJLabel))
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(ordemLocalJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(ordemStatusAtualJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(atualizarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoAEditarJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloJLabel))
                .addGap(88, 88, 88))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(tituloJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ordemStatusAtualJLabel)
                    .addComponent(ordemIDJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ordemLocalJLabel)
                    .addComponent(ordemDescricaoJLabel))
                .addGap(18, 18, 18)
                .addComponent(campoAEditarJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoAEditarJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(atualizarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(cancelarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoAEditarJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoAEditarJComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoAEditarJComboBoxActionPerformed

    private void atualizarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarJButtonActionPerformed
        String novoStatus = campoAEditarJComboBox.getSelectedItem().toString();

        // Aqui você deve chamar um método do seu controlador que atualiza a ordem no arquivo CSV.
        // Supondo que você tenha um método chamado `atualizarStatusOrdem` no seu controlador:
        String ordemId = ordemIDJLabel.getText().replaceAll("[^0-9]", ""); // Obtém o ID da ordem
        boolean sucesso = this.ordemController.atualizarStatusOrdem(ordemId, novoStatus); // Atualiza o status

        if (sucesso) {
            JOptionPane.showMessageDialog(this, "Status da ordem atualizado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); // Fecha o diálogo
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao atualizar o status da ordem.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_atualizarJButtonActionPerformed

    private void cancelarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelarJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtualizarStatusJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtualizarStatusJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtualizarStatusJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtualizarStatusJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AtualizarStatusJDialog dialog = new AtualizarStatusJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atualizarJButton;
    private javax.swing.JComboBox<String> campoAEditarJComboBox;
    private javax.swing.JLabel campoAEditarJLabel;
    private javax.swing.JButton cancelarJButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ordemDescricaoJLabel;
    private javax.swing.JLabel ordemIDJLabel;
    private javax.swing.JLabel ordemLocalJLabel;
    private javax.swing.JLabel ordemStatusAtualJLabel;
    private javax.swing.JLabel tituloJLabel;
    // End of variables declaration//GEN-END:variables
}
