/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.predium.view;

import com.mycompany.predium.FileWatcher;
import com.mycompany.predium.controller.CadastroHandler;
/**
 *
 * @author MarquesV
 */
import com.mycompany.predium.controller.LoginHandler;
import com.mycompany.predium.model.Usuario;
import com.mycompany.predium.utils.KeyboardUtils;
import com.mycompany.predium.utils.PlaceholderField;
import com.mycompany.predium.utils.WindowUtils;
import java.awt.event.KeyEvent;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

public class LoginJFrame extends javax.swing.JFrame {

    private LoginHandler loginHandler;
    private CadastroHandler cadastroHandler;

    public LoginJFrame(CadastroHandler cadastroHandler) {
        initComponents();
        WindowUtils.centralizarTela(this);
        new PlaceholderField(jPasswordField);
        this.cadastroHandler = cadastroHandler;
        loginHandler = new LoginHandler(cadastroHandler.getUsuarios());

        KeyboardUtils.setTabFocus(usernameJTextArea);
        KeyboardUtils.setTabFocus(jPasswordField);
        KeyboardUtils.setTabFocus(entrarJButton);
        KeyboardUtils.setTabFocus(registrarJButton);
        KeyboardUtils.configurarEnterParaBotao(entrarJButton);
        KeyboardUtils.configurarEnterParaBotao(registrarJButton);

        Path path = Paths.get("src/main/resources/db");
        new FileWatcher(path, loginHandler).start(); // Inicia o monitoramento do arquivo de usuários
    }

    public LoginHandler getLoginHandler() {
        return loginHandler;
    }

    public void atualizarUsuarios(List<Usuario> novosUsuarios) {
        loginHandler.atualizarUsuarios(novosUsuarios);

        // Imprime informações sobre novos usuários
        for (Usuario usuario : novosUsuarios) {
            System.out.println("Usuário adicionado! Username do novo usuário: " + usuario.getUsername());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJPanel = new javax.swing.JPanel();
        loginJPanel = new javax.swing.JPanel();
        loginTitleJLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        usernameJLabel = new javax.swing.JLabel();
        senhaJLabel = new javax.swing.JLabel();
        entrarJButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        cadastreJLabel = new javax.swing.JLabel();
        registrarJButton = new javax.swing.JButton();
        jPasswordField = new javax.swing.JPasswordField();
        usernameJScrollPanel = new javax.swing.JScrollPane();
        usernameJTextArea = new javax.swing.JTextArea();
        imgLogoJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - Predium");
        setBackground(new java.awt.Color(0, 255, 0));
        setFocusable(false);
        setName("loginJFrame"); // NOI18N
        setResizable(false);

        mainJPanel.setBackground(new java.awt.Color(245, 245, 245));
        mainJPanel.setFocusable(false);

        loginJPanel.setBackground(new java.awt.Color(121, 203, 180));
        loginJPanel.setFocusable(false);
        loginJPanel.setRequestFocusEnabled(false);

        loginTitleJLabel.setBackground(new java.awt.Color(37, 57, 71));
        loginTitleJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginTitleJLabel.setForeground(new java.awt.Color(37, 57, 71));
        loginTitleJLabel.setText("Login");
        loginTitleJLabel.setFocusable(false);

        usernameJLabel.setBackground(new java.awt.Color(37, 57, 71));
        usernameJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernameJLabel.setForeground(new java.awt.Color(37, 57, 71));
        usernameJLabel.setText("Username");
        usernameJLabel.setFocusable(false);

        senhaJLabel.setBackground(new java.awt.Color(37, 57, 71));
        senhaJLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        senhaJLabel.setForeground(new java.awt.Color(37, 57, 71));
        senhaJLabel.setText("Senha");
        senhaJLabel.setFocusable(false);

        entrarJButton.setBackground(new java.awt.Color(39, 57, 69));
        entrarJButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        entrarJButton.setForeground(new java.awt.Color(255, 255, 255));
        entrarJButton.setText("ENTRAR");
        entrarJButton.setFocusTraversalPolicyProvider(true);
        entrarJButton.setNextFocusableComponent(registrarJButton);
        entrarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarJButtonActionPerformed(evt);
            }
        });

        jSeparator3.setRequestFocusEnabled(false);

        cadastreJLabel.setBackground(new java.awt.Color(37, 57, 71));
        cadastreJLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cadastreJLabel.setForeground(new java.awt.Color(37, 57, 71));
        cadastreJLabel.setText("Cadastre-se");
        cadastreJLabel.setFocusable(false);

        registrarJButton.setBackground(new java.awt.Color(39, 57, 69));
        registrarJButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registrarJButton.setForeground(new java.awt.Color(255, 255, 255));
        registrarJButton.setText("CADASTRAR");
        registrarJButton.setFocusTraversalPolicyProvider(true);
        registrarJButton.setNextFocusableComponent(usernameJTextArea);
        registrarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarJButtonActionPerformed(evt);
            }
        });

        jPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPasswordField.setForeground(new java.awt.Color(36, 60, 69));
        jPasswordField.setText("jPasswordField1");
        jPasswordField.setToolTipText("Insira sua senha");
        jPasswordField.setActionCommand("null");
        jPasswordField.setFocusTraversalPolicyProvider(true);
        jPasswordField.setNextFocusableComponent(entrarJButton);
        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        usernameJScrollPanel.setFocusable(false);

        usernameJTextArea.setBackground(new java.awt.Color(255, 255, 255));
        usernameJTextArea.setColumns(20);
        usernameJTextArea.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernameJTextArea.setForeground(new java.awt.Color(36, 60, 69));
        usernameJTextArea.setRows(1);
        usernameJTextArea.setToolTipText("Insira seu username");
        usernameJTextArea.setFocusTraversalPolicyProvider(true);
        usernameJTextArea.setNextFocusableComponent(jPasswordField);
        usernameJScrollPanel.setViewportView(usernameJTextArea);

        javax.swing.GroupLayout loginJPanelLayout = new javax.swing.GroupLayout(loginJPanel);
        loginJPanel.setLayout(loginJPanelLayout);
        loginJPanelLayout.setHorizontalGroup(
            loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(senhaJLabel)
                    .addGroup(loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPasswordField)
                        .addComponent(entrarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cadastreJLabel)
                        .addComponent(loginTitleJLabel)
                        .addComponent(usernameJLabel)
                        .addComponent(jSeparator2)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(registrarJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usernameJScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        loginJPanelLayout.setVerticalGroup(
            loginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(loginTitleJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(usernameJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(usernameJScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(senhaJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(entrarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cadastreJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(registrarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        imgLogoJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLogoJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/predium-logo+text.png"))); // NOI18N
        imgLogoJLabel.setText("jLabel6");
        imgLogoJLabel.setFocusable(false);
        imgLogoJLabel.setRequestFocusEnabled(false);

        javax.swing.GroupLayout mainJPanelLayout = new javax.swing.GroupLayout(mainJPanel);
        mainJPanel.setLayout(mainJPanelLayout);
        mainJPanelLayout.setHorizontalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(loginJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(imgLogoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        mainJPanelLayout.setVerticalGroup(
            mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJPanelLayout.createSequentialGroup()
                .addGroup(mainJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainJPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(loginJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainJPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(imgLogoJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarJButtonActionPerformed
        // TODO add your handling code here:
        CadastroJFrame cadastroFrame = new CadastroJFrame(this, cadastroHandler, loginHandler);
        cadastroFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registrarJButtonActionPerformed

    private void entrarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarJButtonActionPerformed
        String username = usernameJTextArea.getText();
        String senha = new String(jPasswordField.getPassword());
        System.out.println("Username: " + username);
        System.out.println("Senha: " + senha);

        // Chama o método login e verifica o retorno
        boolean loginSucesso = loginHandler.login(username, senha);

        if (loginSucesso) {
            // Fecha o LoginJFrame e abre a tela principal
            PrincipalJFrame principalFrame = new PrincipalJFrame(username, loginHandler);
            principalFrame.setVisible(true);
            this.dispose(); // Fecha a janela de login

        } else {
            // Exibe uma mensagem de erro ou faz alguma ação em caso de falha de login
            javax.swing.JOptionPane.showMessageDialog(this, "Usuário ou senha incorretos.");
        }
    }//GEN-LAST:event_entrarJButtonActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // Cria um CadastroHandler dummy para passar para o LoginJFrame
            CadastroHandler dummyCadastroHandler = new CadastroHandler();
            new LoginJFrame(dummyCadastroHandler).setVisible(true);
        });
    }

    public CadastroHandler getCadastroHandler() {
        return cadastroHandler;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cadastreJLabel;
    private javax.swing.JButton entrarJButton;
    private javax.swing.JLabel imgLogoJLabel;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel loginJPanel;
    private javax.swing.JLabel loginTitleJLabel;
    private javax.swing.JPanel mainJPanel;
    private javax.swing.JButton registrarJButton;
    private javax.swing.JLabel senhaJLabel;
    private javax.swing.JLabel usernameJLabel;
    private javax.swing.JScrollPane usernameJScrollPanel;
    private javax.swing.JTextArea usernameJTextArea;
    // End of variables declaration//GEN-END:variables
}
