/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.predium.view;

import com.mycompany.predium.controller.OrdemServicoController;
import com.mycompany.predium.controller.TecnicoController;
import com.mycompany.predium.model.Tecnico;
import com.mycompany.predium.utils.TableUtils;
import com.mycompany.predium.utils.WindowUtils;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MarquesV
 */
public class RelatoriosJFrame extends javax.swing.JFrame {

    private OrdemServicoController ordemController;
    private TecnicoController tecnicoController;

    /**
     * Creates new form RelatoriosJFrame
     */
    public RelatoriosJFrame() {
        initComponents();
        WindowUtils.centralizarTela(this);
        this.ordemController = new OrdemServicoController();
        this.tecnicoController = new TecnicoController();

        // Seleciona o radioButton "Todas" por padrão
        todasjRadioButton.setSelected(true);

        // Configura a tabela inicialmente com todas as ordens
        carregarOrdensParaTabela("Todas");
        TableUtils.configurarCoresOrdemServico(ordensJTable, 5);
        TableUtils.configureNonEditableTable(ordensJTable);
        // Adiciona listeners para todos os radioButtons
        todasjRadioButton.addActionListener(e -> carregarOrdensParaTabela("Todas"));
        abertasjRadioButton.addActionListener(e -> carregarOrdensParaTabela("Aberta"));
        andamentojRadioButton.addActionListener(e -> carregarOrdensParaTabela("Andamento"));
        concluidasjRadioButton.addActionListener(e -> carregarOrdensParaTabela("Concluída"));
        canceladasjRadioButton.addActionListener(e -> carregarOrdensParaTabela("Cancelada"));
    }

    private void carregarOrdensParaTabela(String filtroStatus) {
        List<String[]> todasOrdens = ordemController.carregarOrdensServicoString();

        String[] colunas = {"ID", "Descrição", "Local", "Data de Entrada", "Prioridade", "Status", "Técnico"};
        DefaultTableModel tableModel = TableUtils.createNonEditableModel(colunas);

        for (String[] ordem : todasOrdens) {
            // Verifica se deve incluir a ordem baseado no filtro
            if (filtroStatus.equals("Todas") || ordem[5].equals(filtroStatus)) {
                // Substitui o ID do técnico pelo nome
                if (!ordem[6].equals("null")) {
                    try {
                        int tecnicoId = Integer.parseInt(ordem[6]);
                        Tecnico tecnico = tecnicoController.buscarTecnicoPorId(tecnicoId);
                        if (tecnico != null) {
                            ordem[6] = tecnico.getNome();
                        } else {
                            ordem[6] = "Técnico não encontrado";
                        }
                    } catch (NumberFormatException e) {
                        ordem[6] = "ID inválido";
                    }
                } else {
                    ordem[6] = "Não atribuído";
                }

                tableModel.addRow(ordem);
            }
        }

        ordensJTable.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcaoButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cancelarJButton = new javax.swing.JButton();
        gerarRelatorioCSVJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        todasjRadioButton = new javax.swing.JRadioButton();
        abertasjRadioButton = new javax.swing.JRadioButton();
        andamentojRadioButton = new javax.swing.JRadioButton();
        concluidasjRadioButton = new javax.swing.JRadioButton();
        canceladasjRadioButton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordensJTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatórios - Predium");
        setName("Relatorios"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Relatórios");

        cancelarJButton.setBackground(new java.awt.Color(187, 187, 187));
        cancelarJButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cancelarJButton.setForeground(new java.awt.Color(0, 0, 0));
        cancelarJButton.setText("Cancelar");
        cancelarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarJButtonActionPerformed(evt);
            }
        });

        gerarRelatorioCSVJButton.setBackground(new java.awt.Color(30, 149, 115));
        gerarRelatorioCSVJButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        gerarRelatorioCSVJButton.setForeground(new java.awt.Color(255, 255, 255));
        gerarRelatorioCSVJButton.setText("Gerar Relatório CSV");
        gerarRelatorioCSVJButton.setFocusTraversalPolicyProvider(true);
        gerarRelatorioCSVJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarRelatorioCSVJButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Selecione a opção desejada:");

        opcaoButtonGroup.add(todasjRadioButton);
        todasjRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        todasjRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        todasjRadioButton.setSelected(true);
        todasjRadioButton.setText("Todas");
        todasjRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todasjRadioButtonActionPerformed(evt);
            }
        });

        opcaoButtonGroup.add(abertasjRadioButton);
        abertasjRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        abertasjRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        abertasjRadioButton.setText("Abertas");

        opcaoButtonGroup.add(andamentojRadioButton);
        andamentojRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        andamentojRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        andamentojRadioButton.setText("Andamento");
        andamentojRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andamentojRadioButtonActionPerformed(evt);
            }
        });

        opcaoButtonGroup.add(concluidasjRadioButton);
        concluidasjRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        concluidasjRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        concluidasjRadioButton.setText("Concluídas");

        opcaoButtonGroup.add(canceladasjRadioButton);
        canceladasjRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        canceladasjRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        canceladasjRadioButton.setText("Canceladas");

        ordensJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Descrição", "Local", "Prioridade", "Técnico", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ordensJTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        ordensJTable.setFocusable(false);
        ordensJTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ordensJTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ordensJTable.getTableHeader().setResizingAllowed(false);
        ordensJTable.getTableHeader().setReorderingAllowed(false);
        ordensJTable.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(ordensJTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(todasjRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                        .addGap(109, 109, 109))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(abertasjRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(34, 34, 34)
                                .addComponent(andamentojRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                .addGap(32, 32, 32)
                                .addComponent(concluidasjRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addGap(33, 33, 33)
                                .addComponent(canceladasjRadioButton)
                                .addGap(112, 112, 112)))
                        .addComponent(gerarRelatorioCSVJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cancelarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(96, 96, 96))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(canceladasjRadioButton)
                    .addComponent(concluidasjRadioButton)
                    .addComponent(andamentojRadioButton)
                    .addComponent(abertasjRadioButton)
                    .addComponent(todasjRadioButton))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gerarRelatorioCSVJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelarJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarJButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelarJButtonActionPerformed

    private void gerarRelatorioCSVJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarRelatorioCSVJButtonActionPerformed
// Determina o filtro selecionado
        String filtroSelecionado = "Todas";
        if (abertasjRadioButton.isSelected()) {
            filtroSelecionado = "Aberta";
        } else if (andamentojRadioButton.isSelected()) {
            filtroSelecionado = "Em Andamento";
        } else if (concluidasjRadioButton.isSelected()) {
            filtroSelecionado = "Concluída";
        } else if (canceladasjRadioButton.isSelected()) {
            filtroSelecionado = "Cancelada";
        }

        // Cria nome do arquivo com data/hora
        SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd_HHmmss");
        String dataHora = sdf.format(new Date());
        String nomeArquivoSugerido = "relatorio_" + filtroSelecionado.toLowerCase() + "_" + dataHora + ".csv";

        // Abre diálogo para salvar arquivo
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setSelectedFile(new File(nomeArquivoSugerido));
        fileChooser.setFileFilter(new FileNameExtensionFilter("Arquivos CSV (*.csv)", "csv"));

        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File arquivoSelecionado = fileChooser.getSelectedFile();

            // Adiciona extensão .csv se necessário
            if (!arquivoSelecionado.getName().toLowerCase().endsWith(".csv")) {
                arquivoSelecionado = new File(arquivoSelecionado.getAbsolutePath() + ".csv");
            }

            try (BufferedWriter writer = new BufferedWriter(new FileWriter(arquivoSelecionado))) {
                // Escreve cabeçalho
                writer.write("ID,Descrição,Local,Data de Entrada,Prioridade,Status,Técnico\n");

                // Pega modelo da tabela atual (já filtrada)
                DefaultTableModel model = (DefaultTableModel) ordensJTable.getModel();

                // Escreve dados
                for (int i = 0; i < model.getRowCount(); i++) {
                    StringBuilder linha = new StringBuilder();
                    for (int j = 0; j < model.getColumnCount(); j++) {
                        if (j > 0) {
                            linha.append(",");
                        }
                        String valor = model.getValueAt(i, j).toString();
                        // Escapa aspas duplas e adiciona aspas ao redor do valor se contiver vírgula
                        if (valor.contains(",") || valor.contains("\"") || valor.contains("\n")) {
                            valor = "\"" + valor.replace("\"", "\"\"") + "\"";
                        }
                        linha.append(valor);
                    }
                    writer.write(linha.toString());
                    writer.newLine();
                }

                JOptionPane.showMessageDialog(this,
                        "Relatório gerado com sucesso!\nSalvo em: " + arquivoSelecionado.getAbsolutePath(),
                        "Sucesso",
                        JOptionPane.INFORMATION_MESSAGE);

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this,
                        "Erro ao gerar relatório: " + e.getMessage(),
                        "Erro",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_gerarRelatorioCSVJButtonActionPerformed

    private void todasjRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todasjRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_todasjRadioButtonActionPerformed

    private void andamentojRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andamentojRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_andamentojRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatoriosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatoriosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatoriosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatoriosJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatoriosJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton abertasjRadioButton;
    private javax.swing.JRadioButton andamentojRadioButton;
    private javax.swing.JRadioButton canceladasjRadioButton;
    private javax.swing.JButton cancelarJButton;
    private javax.swing.JRadioButton concluidasjRadioButton;
    private javax.swing.JButton gerarRelatorioCSVJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup opcaoButtonGroup;
    private javax.swing.JTable ordensJTable;
    private javax.swing.JRadioButton todasjRadioButton;
    // End of variables declaration//GEN-END:variables
}
